const express = require('express')
const ejs = require('ejs')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
// const { MongoClient } = require('mongodb')
mongoose.connect('mongodb+srv://ricktheCoder:Godblessme@blogcluster.fkfbwdk.mongodb.net/', { useNewUrlParser: true })
const indexJs = require('./routes/index')
const abouts = require('./routes/about')
const contact = require('./routes/contact')
const posts = require('./routes/post')
const createposts = require('./routes/create')
const formdata = require('./routes/formdata')
const blogpost = require('./routes/blogposts')
const app = express()
app.use(express())
app.use(express.static('public'))
app.set('view engine', 'ejs')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.use(indexJs)
app.use(abouts)
app.use(contact)
app.use(posts)
app.use(createposts)
app.use(formdata)
app.use(blogpost)

module.exports = app
