const express = require('express')
const path = require('path')
const ejs = require('ejs')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const fileUpload = require('express-fileupload')
const expressSession = require('express-session')
// const { MongoClient } = require('mongodb')
const { DB_URL } = require('./props')
mongoose.connect(DB_URL, { useNewUrlParser: true }).then(() => console.log('db connected'))

const validateMiddleware = require('./middleware/validationMiddleware')
const authMiddleware = require('./middleware/authMiddleware')
const aboutPageRoute = require('./routes/aboutPage')
const contactPageRoute = require('./routes/contactPage')
const postsRouter = require('./routes/getpostRoutes')
const createPageRoute = require('./routes/createPage')
const storePostsRouter = require('./routes/storePosts')
const indexRouter = require('./routes/indexPosts')
const newUserRouter = require('./routes/newUser')
const storeUserRouter = require('./routes/storeUser')
const loginRouter = require('./routes/login')
const loginUserRouter = require('./routes/loginUser')

const app = express()
app.use(express())
app.use(expressSession({ secret: 'keyboard cat' }))
app.use(express.static('public'))
app.set('view engine', 'ejs')
app.set('views', path.join(__dirname, 'views'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(fileUpload())

app.use('/posts/store', validateMiddleware)
app.get('/about', aboutPageRoute)
app.get('/contact', contactPageRoute)
app.get('/post/:id', postsRouter)
app.get('/posts/new', authMiddleware, createPageRoute)
app.post('/posts/store', authMiddleware, storePostsRouter)
app.get('/', indexRouter)
app.get('/auth/register', newUserRouter)
app.post('/users/register', storeUserRouter)
app.get('/auth/login', loginRouter)
app.post('/users/login', loginUserRouter)

module.exports = app
